import createMiddleware from "next-intl/middleware";
import { routing } from "./i18n/routing";

export default createMiddleware(routing);

export const config = {
  // Exclude API/internal paths, anything with a file extension (sitemap.xml,
  // robots.txt, …), and the extensionless icon metadata route generated by
  // src/app/icon.tsx — otherwise it gets a locale prefix and 404s.
  matcher: ["/((?!api|_next|_vercel|icon|.*\\..*).*)"],
};
